### ISSUE TITLE
Feed File Generation rework.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/facebook-for-woocommerce#1904]
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1632 Move Feed Actions away from init hook
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1723 Products sync twice (with different Content-ID)
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1726 Does not sync
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1775 Variable products' category does not sync to Facebook
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1755 Product Time Synchronisation problem in WooCommerce and Facebook Catalog
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1737 Duplicated products in FB Shop
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1818 PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 5242880 bytes) in /wordpress/core/5.7/wp-includes/class-wp-query.php on line 2986
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1841 Improve performance of full product sync with large number of products
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1871 wc_facebook_regenerate_feed Out of Memory issues since 2.3.2
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1894 Verify fields in feed file. (@rcstr )
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1895 Tune feed generation batch size and Action Scheduler Queue.
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1896 Prepare UI for feed file status page.
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1897 Support fetching of the feed file by facebook catalog data source.
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1898 Exclude products from the feed file that should not be synced.
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1899 Add logging to the feed generation process.
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1900 Update feed generation documentation.
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1901 Implement feed generation using WooCoommerce CSV generation class
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1902 Cleanup remaining feed code and remove old feed functionality.
- [ ] https://github.com/woocommerce/facebook-for-woocommerce/issues/1903 Create feed file with upload schedule. ( @rcstr )
