### ISSUE TITLE
Remove Sake from the Project repo.

### ISSUE THREAD

**Issue by rawdreeg** [woocommerce/facebook-for-woocommerce#2290]
## Motivation

We're only using the sake build tool to bundle the plugin zip, and we've been using Woorelease on the project for deployment (#1946).

I suggest dropping sake as a dependency on the project and user composer archive to bundle the project zip. 

##  Tasks
- [ ] Remove the language folder from the repository. (#1954)
- [ ] Implement bundling through composer archive.
- [ ] Remove sake as a dependency
- [ ] Update readme md to remove sake.

**Comment by rawdreeg** [comment]
@budzanowski, @message-dimke Please let me know if I missed any other tasks we need to close for this.
